backend:
  name: git-gateway
  repo: pedjamusic/milan-vucinic
  branch: main
  identity_url: "https://milan-vucinic.netlify.app/.netlify/identity"
  gateway_url: "https://milan-vucinic.netlify.app/.netlify/git"

# when using the default proxy server port; npx netlify-cms-proxy-server
local_backend: true

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

media_library:
  name: cloudinary
  config:
    username: hi@iampedja.com
    cloud_name: too-dear
    api_key: '528391217167367'
    multiple: true
    default_transformations:
      - - fetch_format: auto
          width: 800
          quality: auto
          crop: scale

collections:
  - label: Sections
    name: sections
    label_singular: section
    description: "Applicant personal information, as well as experience, courses, education, etc."
    files:
      - name: personal
        label: "Personal info"
        delete: false
        editor:
          preview: false
        file: content/personal.json
        extension: json
        fields:
          - { label: Category, name: category, widget: hidden, default: personal }
          - { label: Photo, name: photo, widget: image, allow_multiple: false }
          - { label: "Full Name", name: name, default: "John Appleseed" }
          - { label: Vocation, name: vocation, default: "Engineer" }
          - { label: "Date of Birth", name: dob, widget: date, format: "D.M.YYYY." }
          - { label: E-Mail, name: email }
          - { label: "Contact Phone", name: tel }
          - { label: "Marital Status", name: marriage, required: false, widget: select, options: ["Yes", "No", "Prefer not to say"], default: "Prefer not to say"}
          - { label: Quote, name: quote, required: false, default: null }
      - name: "jobs"
        label: "Jobs"
        file: content/jobs.json
        extension: json
        editor:
          preview: false
        fields:
          - name: jobs
            label: Jobs
            label_singular: job
            summary: "{{fields.title}} @{{fields.employer}}"
            widget: list
            fields:
              - { label: Category, name: category, widget: hidden, default: jobs }
              - { label: Title, name: title }
              - { label: Employer, name: employer }
              - { label: "Start Date", name: startdate, widget: date, date_format: "YYYY. MM.", format: "YYYY-MM" }
              - { label: "End Date", name: enddate, widget: datetime, date_format: "YYYY. MM.", format: "YYYY-MM" }
              - { label: Location, name: location, required: false }
              - { label: Details, name: details, widget: markdown, required: false, default: null }
              - { label: Gallery, name: gallerysrc, widget: image, allow_multiple: true, required: false }
      - name: "education"
        label: "Education"
        file: content/education.json
        extension: json
        editor:
          preview: false
        fields:
          - name: education
            label: education
            summary: "{{fields.degree}} - {{fields.fos}}"
            widget: list
            fields:
              - { label: Category, name: category, widget: hidden, default: education }
              - { label: Degree, name: degree, widget: select, options: ["Bachelor", "Master", "Doctor", "Certificate"] }
              - { label: "Field of Studies", name: fos }
              - { label: University, name: university }
              - { label: "Start Date", name: startdate, widget: date, format: "YYYY-MM" }
              - { label: "End Date", name: enddate, widget: date, format: "YYYY-MM" }
              - { label: Details, name: details, widget: markdown, required: false, default: null }
              - { label: Gallery, name: gallerysrc, widget: image, allow_multiple: true, required: false }
      - name: "courses"
        label: "Courses"
        label_singular: "course"
        file: content/courses.json
        extension: json
        editor:
          preview: false
        fields:
          - name: courses
            label: Courses
            label_singular: course
            summary: "{{fields.coursename}}"
            widget: list
            fields:
              - { label: "Course Name", name: coursename }
              - { label: Issuer, name: issuer, required: false, default: null }
      - name: achievements
        label: Achievements
        label_singular: achievement
        file: content/achievements.json
        extension: json
        editor:
          preview: false
        fields:
          - name: achievements
            label: Achievements
            label_singular: achievement
            summary: "{{fields.year}} {{fields.event}}"
            widget: list
            fields:
              - { label: Event, name: event }
              - { label: Location, name: location, required: false, default: null }
              - { label: Achieved, name: achieved }
              - { label: Year, name: year, widget: date, date_format: "YYYY", format: "YYYY" }