backend:
  name: "github"
  repo: "pedjamusic/milan-vucinic"
  branch: "main"

publish_mode: "editorial_workflow"

media_folder: "images/uploads"
# public_folder: "/assets/uploads"

collections:
  - name: "experience"
    label: "Experience"
    folder: "experience"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "experience" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "title", label: "Title", default: "Experience" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "gallery", label: "Gallery", widget: "image" }
  - name: "education"
    label: "Education"
    folder: "education"
    create: true
    fields:
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "title", label: "Title", default: "Education" }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "courses"
    label: "Courses"
    folder: "courses"
    create: true
    fields:
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "title", label: "Title", default: "Courses" }
      - { name: "body", label: "Body", widget: "markdown" }