backend:
  name: github
  # name: git-gateway
  repo: pedjamusic/milan-vucinic
  branch: main
  identity_url: "https://milan-vucinic.netlify.app/.netlify/identity"
  gateway_url: "https://milan-vucinic.netlify.app/.netlify/git"

publish_mode: editorial_workflow

media_folder: "/src/assets/images/uploads"
# public_folder: "/assets/uploads"

collections:
  - name: "experience"
    label: "Experience"
    folder: "/src/pages/experience"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "experience" }
      - { name: "title", label: "Title" }
      - { name: "employer", label: "Employer" }
      - { name: "description", label: "Description", widget: "markdown" }
      - { name: "gallery", label: "Gallery", widget: "image" }
  - name: "education"
    label: "Education"
    folder: "/src/pages/education"
    create: true
    fields:
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "title", label: "Title", default: "Education" }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "courses"
    label: "Courses"
    folder: "/src/pages/courses"
    create: true
    fields:
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "title", label: "Title", default: "Courses" }
      - { name: "body", label: "Body", widget: "markdown" }