backend:
  # name: github
  name: git-gateway
  repo: pedjamusic/milan-vucinic
  branch: main
  identity_url: "https://milan-vucinic.netlify.app/.netlify/identity"
  gateway_url: "https://milan-vucinic.netlify.app/.netlify/git"

# when using the default proxy server port; npx netlify-cms-proxy-server
local_backend: true

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

collections:
  - label: Sections
    name: sections
    label_singular: section
    description: "Applicant personal information, as well as experience, courses, education, etc."
    files:
      - name: personal
        label: "Personal info"
        delete: false
        editor:
          preview: false
        file: content/personal.md
        extension: md
        fields:
          - { label: Photo, name: photo, widget: image, allow_multiple: false }
          - { label: "Full Name", name: name, default: "John Appleseed" }
          - { label: Vocation, name: vocation, default: "Engineer" }
          - { label: "Date of Birth", name: dob, widget: date, format: "D.M.YYYY." }
          - { label: E-Mail, name: email }
          - { label: "Contact Phone", name: tel }
          - { label: "Marital Status", name: marriage, required: false, widget: select, options: ["Yes", "No", "Preffer not to say"]}
          - { label: Quote, name: quote, required: false, default: "Lorem ipsum, dolor sit amet consectetur adipisicing elit." }
      - name: 'jobs'
        label: 'Jobs'
        file: content/jobs.json
        extension: json
        editor:
          preview: false
        fields:
          - name: jobs
            label: Jobs
            label_singular: jobs
            summary: "{{fields.title}} @{{fields.employer}}"
            widget: list
            fields:
              - { label: Category, name: category, widget: hidden, default: jobs }
              - { label: Title, name: title }
              - { label: Employer, name: employer }
              - { label: "Start Date", name: startdate, widget: date, format: "YYYY-MM" }
              - { label: "End Date", name: enddate, widget: datetime, format: "YYYY-MM" }
              - { label: Location, name: location, required: false }
              - { label: Description, name: description, widget: markdown, required: false }
              - { label: Gallery, name: gallery, widget: image, allow_multiple: true, required: false }
      - name: 'education'
        label: 'Education'
        file: content/education.json
        extension: json
        editor:
          preview: false
        fields:
          - name: education
            label: education
            summary: "{{fields.degree}}"
            widget: list
            fields:
              - { label: Category, name: category, widget: hidden, default: education }
              - { label: Degree, name: degree, widget: select, options: ["Bachelor", "Master", "Doctor", "Certificate"] }
              - { label: "Field of Studies", name: fos }
              - { label: University, name: university }
              - { label: "Start Date", name: startdate, widget: date, format: "YYYY-MM" }
              - { label: "End Date", name: enddate, widget: date, format: "YYYY-MM" }
              - { label: Description, name: description, widget: markdown, required: false }
              - { label: Gallery, name: gallery, widget: image, allow_multiple: true, required: false }