backend:
  # name: github
  name: git-gateway
  repo: pedjamusic/milan-vucinic
  branch: main
  identity_url: "https://milan-vucinic.netlify.app/.netlify/identity"
  gateway_url: "https://milan-vucinic.netlify.app/.netlify/git"

# when using the default proxy server port; npx netlify-cms-proxy-server
local_backend: true

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

collections:
  - label: Sections
    name: sections
    files:
      - label: "Personal info"
        name: personal
        file: content/personal.json
        extension: json
        description: "Personal Information of The User"
        fields:
          - { label: "Your name", name: name, default: "John Appleseed" }
          - { label: Vocation, name: vocation, default: "Engineer" }
          - { label: Quote, name: quote, default: "Lorem ipsum, dolor sit amet consectetur adipisicing elit." }
          - { label: Photo, name: photo, widget: image, allow_multiple: false }
      - label: Jobs
        name: jobs
        # folder: content/jobs
        file: content/jobs.json
        create: true
        widget: list
        allow_add: true
        fields:
          - { label: Category, name: category, widget: hidden, default: jobs }
          - { label: Title, name: title }
          - { label: "Start Date", name: startdate, widget: date, format: "YYYY-MM" }
          - { label: "End Date", name: enddate, widget: date, format: "YYYY-MM" }
          - { label: Employer, name: employer }
          - { label: Location, name: location, required: false }
          - { label: Description, name: description, widget: markdown }
          - { label: Gallery, name: gallery, widget: image, allow_multiple: true, required: false }