backend:
  name: github
  repo: pedjamusic/milan-vucinic
  branch: main

publish_mode: editorial_workflow

media_folder: "static/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: resume
    label: Resume
    folder: resume
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }